version: '3.8'

services:
  app:
    image: registry.digitalocean.com/fullstack-kea/frontendv2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=production
